project_name: Default
working_dir: src\Visual_Model
cmd:
- python DDAMFN.py
provisioning:
  gpu_type: a10g
  gpu_count: 1
  cpu_count: 32
  ram: 128
teamcity:
  url: https://mlops.staging.sandbox.teamcity.aws.intellij.net
  build_conf_id: Aeadd066608f4afe95d7e8f4a2068b6b_JetTrain
env:
  variables:
    PYTHONUNBUFFERED: "1"
  python:
    pip:
      requirements_path: requirements.txt
    version: 3.12.0
  secrets:
    variables: {}
    ssh_keys: []
  aws:
    sync_config: false
    sync_credentials: false
    sync_cache: false
project_sync:
  local:
    root: "."
    storage_name: Cadence Storage
    uri: ""
    exclude:
    - /.venv/**
    include:
    - /src/Visual_Model/V2_FPS16_AUGMENTS
    sync_back: false
    snapshots: true
    storage_type: DEFAULT
inputs: []
outputs:
- type: OUTPUT
  storage_name: Cadence Storage
  uri: ""
  path: "."
  acceleration: false
  storage_type: DEFAULT
mounts: []
storages:
- name: Cadence Storage
  storage_type: s3
  credentials:
    access_key_id: ASIASYCYVCDCR5NZJ3D2
    secret_access_key: jd0F4KTdmdKOoLuLy72rX20WBoAJt9f5mJZuEjKt
    session_token: IQoJb3JpZ2luX2VjEAUaCWV1LXdlc3QtMSJHMEUCIQDFAumlbqwv4csACTQkB9C2UikxcDXj8etBSk/f8edUOQIgG9d3nMONIgal36I7JqxJHmsDnAKgy1zq2JVFrEM3lt4q2wUIrv//////////ARABGgwxODkxNjQ0OTA5NDkiDF7nY3GtvWU1mqU4iyqvBc1jxcuMnUULqLPC1goQCIL36Y9yKvEPml+PlUPQTD2gVMwyXNHcUrHsOyfBaL15UPc6Ik92PvoF0IrGMQhjUEIrMF4gpIe3sOs2pp6P8PiKuSXIHBcfkwWDQvYzcWtE43okMveckFMqoZfN7CRmsK3aRdxd3A+mGfq6ICLDR9rdfnAy2NItWwXGVO03d6j94iNcUqEIyitswyS/mwUwqJ8NkU/6FxCahBN6X2DZxNyEIeZgGp9hUaqfKBQDU3GXzlW4yxKpkDaLztniyBztaF3hf/Ng+KbvMN6TYkr5ujC55//kefbQ1QQZ3eUvoi3GT+1S4Cms+jAiTfGQpw7AaWJYDK1qJdu80wdGwDseaQXrlCU5FqW/dmm5oMSv3KHANBQPyOeUdypw60Q1g6l/SysoerqV8Rq1GDR7UcOQqjt8NJjLaD8LzI33hInHCCE1FM6Iu0bQueLmwnUsZewIz8mHWUPAajA3r+BHzctu+sDJDoOC5b1Rp5RkBKEpoCsIBcdzc1ATMDepMipb0wkf6EQp5XSd4Bzfp569a0JbnGQiG4/xFUwSP5E0056DhnDbQya3Vvdep4xCXOOHxorjbOsmqj6aRAwEbV5LM7Osdjuxg34hSPQY3gOVDrvucQx0MWek2on9I5jokvcE3QW0Eh9LIjJVC5bFYhtILJoWZDlzsRGLB6cMloRQUISUTBJ1h2nOJknsCboQNb4NZ4wgVO3LmpgeOCTkfZgRO5sTdNTaSfSIT7ghF7LcKyX+w8Btdtxs7zQoCot9JBy7FnWcAqtfOr9CxHXg7lwA5sB7tRw13dtrk0jL8ZkbPNIntqmVYa4GpOxnxlEKstCc27/zUed7fLxYfIZ+CN33ohj/TeoWtaFKtcbEr1MXJAeuaLPPyz5GZhFRm8WQK/05yhNVezCLlLO6BjqFArYbDYoExH3YPSL6tBRUVdYMmmUhgbPDGoZjjK1B3hBisz4NCZp1KRkE9Iq0BC7V1lhxZAqoc3gZjHdgNEc5Ff6peRsLc8OqvLH+MRhJZmt/ptU5Km9NP6yCMeLr8bhWorn2rwNbWLjDkgtFeRzOuuUOoFAMVJ6FL83nikWhj7TLAs+/44+Tj0dMVzsoE7VMvcIs8LkI9Df7mt2/Y5v7ICUhVqhYY3f66eAKQphea3/AFu0eLL4iLpsuw4U/Qor+J6WH/u3SvWtNGOw+kG0Es5jKgSVBSYO6jAdwZhhE6qWpF2dCBHHj2v4XoB7CP7c2tzoYZOcD6ukk/UrtB4XIkLb15VOXxw==
    bucket: jb-cadence-storage
    type: DEFAULT
description: ""
